### GET request to example server
@id = 1
GET http://localhost:8081/api/user/{{id}}
Authorization: eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3Njk1ODI3NjYsImV4cCI6MTc2OTU5MTQwNiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIn0.JYEhvkD4vCmJM9D7yCu21rCVRZ49tcavbixcpassHvHiedw4SqTX1Z2hj8qUaYTc